version: '3.9'

services:
  app:
    image: sergeykelme/portfolio:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - "8000:8000"

  nginx:
    image: nginx:alpine
    volumes:
      - /portfolio_flask/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - /portfolio_flask/static:/app/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
