version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"


  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./static:/app/static
    ports:
      - "80:80"
      - '443:443'
    depends_on:
      - app
