services:
  app:
    image: sergeykelme/portfolio:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - "8000:8000"

  nginx:
    image: nginx:alpine
    volumes:
      - /home/deploy/portfolio_flask/portfolio/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/deploy/portfolio_flask/portfolio/static:/app/static
      - /etc/letsencrypt:/etc/letsencrypt  # Монтируем сертификаты
      - /home/deploy/portfolio_flask/portfolio/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt  # Монтируем сертификаты
      - /home/deploy/portfolio_flask/portfolio/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"